sudo: required
dist: trusty
language: java
jdk:
    - oraclejdk8
    - oraclejdk9
services:
    - docker
before_install:
     - echo 'Installing boost-common lib ....'
     - git clone https://github.com/OpenLiberty/boost-common.git ./boost-common
     - cd ./boost-common
     - mvn clean install
     - cd ..
     - docker run -d -p 5000:5000 --restart=always --name registry registry:2
install: true
script:
  - export GRADLE_OPTS="-Dorg.gradle.daemon=true -Dorg.gradle.jvmargs='-XX:MaxPermSize=1024m -XX:+CMSClassUnloadingEnabled -XX:+HeapDumpOnOutOfMemoryError -Xmx2048m'"
  - travis_wait ./gradlew install check --stacktrace --info --no-daemon

